version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=s3,dynamodb,lambda,sqs,sns

