---
# tasks file for logstash_agent

- name: Ensure server os distribution
  when: ansible_os_family in ["Debian", "Ubuntu"]
  block:
    - name: Check if Logstash is already installed
      ansible.builtin.service_facts:

    - name: Ensure Logstash agent is installed
      when: "'logstash.service' not in services"
      block:
        - name: Install apt-transport-https
          ansible.builtin.apt:
            name: apt-transport-https
            state: present

        - name: Download and install the public signing key
          ansible.builtin.apt_key:
            url: "{{ logstash_agent_public_key_url }}"
            state: present

        - name: Add the Elastic APT repository
          ansible.builtin.apt_repository:
            repo: "{{ logstash_agent_logstash_repo }}"
            state: present

        - name: Update APT cache
          ansible.builtin.apt:
            update_cache: true

        - name: Install Logstash service
          ansible.builtin.apt:
            name: "logstash"
            state: present

    - name: Upload Logstash configuration file
      ansible.builtin.template:
        src: logstash.conf.j2
        dest: "{{ logstash_agent_logstash_config_path }}"
        mode: '0644'

    - name: Check if input file exists
      ansible.builtin.stat:
        path: "{{ logstash_agent_input_log_file }}"
      register: file_stat

    - name: Ensure that input file exists
      ansible.builtin.fail:
        msg: "The file {{ logstash_agent_input_log_file }} does not exist."
      when: not file_stat.stat.exists

    - name: Ensure that input file is readable
      ansible.builtin.file:
        path: "{{ logstash_agent_input_log_file }}"
        group: logstash
        mode: '0640'

    - name: Create output file directory
      ansible.builtin.file:
        path: "{{ logstash_agent_output_log_file | dirname }}"
        state: directory
        mode: '0755'

    - name: Create output file
      ansible.builtin.file:
        path: "{{ logstash_agent_output_log_file }}"
        state: touch
        mode: '0640'

    - name: Change output file ownership to Logstash
      ansible.builtin.file:
        path: "{{ logstash_agent_output_log_file }}"
        owner: logstash
        group: logstash
      notify: Restart logstash service
      changed_when: true
