---
# tasks file for aws_cloudwatch_agent

- name: Ensure CloudWatch agent block tasks
  when: ansible_os_family in ["Debian", "Ubuntu"]
  block:

    - name: Check if CloudWatch agent is already installed
      ansible.builtin.service_facts:

    - name: Ensure CloudWatch agent package handling block
      when: "'amazon-cloudwatch-agent.service' not in services"
      block:

        - name: Check if CloudWatch agent .deb package exists
          ansible.builtin.stat:
            path: "{{ aws_cloudwatch_agent_package_dest }}"
          register: agent_downloaded

        - name: Download CloudWatch agent .deb package
          ansible.builtin.get_url:
            url: "{{ aws_cloudwatch_agent_download_url }}"
            dest: "{{ aws_cloudwatch_agent_package_dest }}"
            mode: '0644'  # Set file permissions
          when: not agent_downloaded.stat.exists

        - name: Install CloudWatch agent
          ansible.builtin.apt:
            deb: "{{ aws_cloudwatch_agent_package_dest }}"
            state: present

    - name: Upload CloudWatch agent configuration file
      ansible.builtin.template:
        src: localstack_config.json.j2
        dest: "{{ aws_cloudwatch_agent_config_path }}"
        mode: '0644'
      register: agent_uploaded

    - name: Deploy CloudWatch agent
      ansible.builtin.command: "{{ aws_cloudwatch_agent_path }} -a fetch-config -m onPremise -c file:{{ aws_cloudwatch_agent_config_path }} -s"
      notify: Restart amazon cloudWatch agent
      changed_when: false
