galaxy_info:
  author: issam
  description: >
    This role installs and configures the logstash agent on
    an on-premises Linux Debian-based server, allowing for
    the log transformation.
  min_ansible_version: "2.1"
  galaxy_tags: []
  license: "no licence"
